delete selected clip
hd-zero/hdzero-goggle pull request #175
Opened 2023-02-24 17:13 UTC by krizmyass

added option to delete selected clip by long pressing right button on page_playback

2023-02-24 22:13 UTC, bkleiner commented
i am fine with going this solution in the interims, but ultimately i think we want a solution like https://github.com/hd-zero/hdzero-goggle/issues/98 to access more advanced options in a given menu. having 5 different keystrokes to trigger different options is gonna get confusing quick.

2023-02-25 04:29 UTC, krizmyass commented
> i am fine with this in the interims, but ultimately i think we want a solution like #98 to access more advanced options in a given menu. having 5 different keystrokes to trigger different options is gonna get confusing quick.

Great. I will work on a context menu.

2023-02-25 14:56 UTC, bkleiner requested changes

2023-02-25 14:56 UTC, bkleiner commented on src/ui/page_playback.c
> +            if (!pnode) {
whitespace, also in following, please use vscode's clangbased autoformat

2023-02-25 14:56 UTC, bkleiner commented on src/ui/page_playback.c
> +                perror("delete_video_file failed. (PNODE ERROR)");
please use `LOGE`

2023-02-25 14:56 UTC, bkleiner commented on src/ui/page_playback.c
> +        perror("delete_video_file successful.");
not an error please use `LOGD`

2023-02-25 14:56 UTC, bkleiner commented on src/ui/page_playback.c
> +        perror("delete_video_file failed.");
please use `LOGE`

2023-02-26 15:22 UTC, bkleiner approved these changes

2023-02-28 13:39 UTC, bkleiner commented
finally got around to testing this - seems to work fine.

2023-02-28 13:39 UTC, merged